name: "Release my package"
on: 
    push:
        tags:
            - '*.*.*-rc'
jobs: 
    ReleaseEcommerce:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet '8.x'
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.x'
            - name: "Create package"
              run: dotnet publish -c Release -o bin/Release/net8.0/publish
        
            - name: Verify files
              run: ls -la bin/Release/net8.0/publish/
        
            - name: Rename file
              run: mv bin/Release/net8.0/publish/*.dll bin/Release/net8.0/publish/ecommerce.dll 
            - uses: ncipollo/release-action@v1
              with:
                name: "My release ${{github.ref}}"
                artifacts: "bin/Release/net8.0/publish/ecommerce.dll"
                body: |
                  # My new release done with GH Action
